[package]
name = "pdf"
version = "0.7.0"
authors = ["Erlend Langseth <3rlendhl@gmail.com>", "Sebastian Köln <s3bk@protonmail.com>"]
repository = "https://github.com/pdf-rs"
readme = "../README.md"
keywords = ["pdf"]
license = "MIT"
documentation = "https://docs.rs/pdf"
edition = "2018"
description = "PDF reader"

[features]
mmap = ["memmap"]
dump = ["tempfile"]
threads = ["jpeg-decoder/default"]
standard-fonts = []

[dependencies]
pdf_derive = "0.1.20"
snafu = "0.4"
num-traits = "0.1.36"
inflate = "0.4.5"
byteorder = "1.0.0"
itertools = "0.6.0"
ordermap = "0.2.9"
memmap = { version = "0.7.0", optional = true }
lzw = "0.10.0"
glob = "0.2.11"
chrono = "0.4.0"
once_cell = "0.2"
log = "0.4.8"
tempfile = { version = "3.1.0", optional = true }
md5 = "0.6"
jpeg-decoder = { version = "0.1", default-features = false }
aes = "0.5.0"
block-modes = "0.6.1"

[lib]
doctest = false
